### ISSUE TITLE
Long response when changing input language

### ISSUE THREAD

**Issue by vykhovanets** [elementary/wingpanel-indicator-keyboard#65]
Almost every time a switch input language by shortcut (in my case Alt + Space) - the next character I type is in my previous input language.

**Comment by shved** [comment]
Same for me. I'd say this problem seem to be general since I encountered it on Mac OS where I waited a small delay before typing to let the layout change before I start type. But anyway on elementary delay is terrible long. Especially when I switch back to us english. It may be related to the fact that IBUS is not working for me (dunno why) so my two layouts are xbs.

**Comment by ryonakano** [comment]
Thanks for your reporting, but closing as a duplicate of elementary/gala#220
