### ISSUE TITLE
NumLock indicator : empty label

### ISSUE THREAD

**Issue by andirsun** [elementary/wingpanel-indicator-keyboard#85]
## What Happened

I just install elementary os 6.0 and set my 2 lenguage keyboard layout (English and spanish)
Then I noticed that numlock indicator has an empty label (when suppose to be a keyboard layout)

![Screenshot from 2020-11-27 17 10 48](https://user-images.githubusercontent.com/22928302/100486791-8dca2500-30d3-11eb-8e72-3fe4556e7823.png)

## Expected Behavior

Show both of my keyboard layouts

## Steps to Reproduce

1.Install eos6.0 daily (27 Nov build)
2.add 2 keyboard layouts
3.see the empty label

**Comment by andirsun** [comment]
This is the keyboard layout 
![Screenshot from 2020-11-27 17-16-14](https://user-images.githubusercontent.com/22928302/100486962-66c02300-30d4-11eb-9b3d-113c95fff4c6.png)

**Comment by jeremypw** [comment]
May be related to #80.  Can you post the value of the setting `org.gnome.desktop.input-sources.sources` ?  You can get this with the terminal command `gsettings get org.gnome.desktop.input-sources sources` or by using the dconf-editor app.

**Comment by andirsun** [comment]
> May be related to #80. Can you post the value of the setting `org.gnome.desktop.input-sources.sources` ? You can get this with the terminal command `gsettings get org.gnome.desktop.input-sources sources` or by using the dconf-editor app.

Sure!, 
```
org.gnome.desktop.input-sources sources [('ibus', 'us'), ('ibus', 'latam')]
```

**Comment by jeremypw** [comment]
This would explain the problem - somehow you have ibus sources rather than xkb layouts.  There is a bug in the switchboard keyboard plug causing this under some circumstances. Wingpanel indicator does not currently recognise ibus sources. Do you have any input methods set up in the next tab?  I am working on some PRs to make the wingpanel indicator work with ibus sources as well as xkb layouts.  Till then, a workaround is to edit the gsetting replacing "ibus" with "xkb" (or remove and readd all the layouts).  Hopefully https://github.com/elementary/switchboard-plug-keyboard/pull/338 will prevent the sources getting unintentionally messed up.

**Comment by andirsun** [comment]
This bug is related with #80, I think must be close it.
